var rule = {
	title:'片刻',
	host:'http://www.0635ad.com/',
	// host:'http://www.5le.cc/',
	// url: '/fyclass/index_fypage.html[/fyclass/index.html]',
	url: '/vod/show/id/fyclassfyfilter.html',
	//http://www.5le.cc/vod/show/by/hits/class/%E5%96%9C%E5%89%A7/id/Series/page/2/year/2023.html
	filter_url:'{{fl.area}}{{fl.by}}{{fl.class}}/page/fypage{{fl.year}}',
	filter:{
		"movie":[{"key":"class","name":"类型","value":[{"n":"全部","v":""},{"n":"古装","v":"/class/古装"},{"n":"剧情","v":"/class/剧情"},{"n":"喜剧","v":"/class/喜剧"},{"n":"惊悚","v":"/class/惊悚"},{"n":"动作","v":"/class/动作"},{"n":"爱情","v":"/class/爱情"},{"n":"犯罪","v":"/class/犯罪"},{"n":"恐怖","v":"/class/恐怖"},{"n":"冒险","v":"/class/冒险"},{"n":"悬疑","v":"/class/悬疑"},{"n":"科幻","v":"/class/科幻"},{"n":"家庭","v":"/class/家庭"},{"n":"奇幻","v":"/class/奇幻"},{"n":"战争","v":"/class/战争"},{"n":"历史","v":"/class/历史"},{"n":"传记","v":"/class/传记"},{"n":"音乐","v":"/class/音乐"},{"n":"歌舞","v":"/class/歌舞"},{"n":"短片","v":"/class/短片"},{"n":"西部","v":"/class/西部"},{"n":"灾难","v":"/class/灾难"},{"n":"情色","v":"/class/情色"},{"n":"同性","v":"/class/同性"},{"n":"儿童","v":"/class/儿童"},{"n":"纪录片","v":"/class/纪录"}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""},{"n":"大陆","v":"/area/大陆"}]},{"key":"year","name":"年代","value":[{"n":"全部","v":""},{"n":"2024","v":"/year/2024"},{"n":"2023","v":"/year/2023"},{"n":"2022","v":"/year/2022"},{"n":"2021","v":"/year/2021"},{"n":"2020","v":"/year/2020"},{"n":"2019","v":"/year/2019"},{"n":"2018","v":"/year/2018"},{"n":"2017","v":"/year/2017"},{"n":"2016","v":"/year/2016"},{"n":"2015","v":"/year/2015"},{"n":"2014","v":"/year/2014"},{"n":"2013","v":"/year/2013"},{"n":"2012","v":"/year/2012"},{"n":"2011","v":"/year/2011"},{"n":"2010","v":"/year/2010"},{"n":"2009","v":"/year/2009"},{"n":"2008","v":"/year/2008"},{"n":"2007","v":"/year/2007"},{"n":"2006","v":"/year/2006"},{"n":"2005","v":"/year/2005"},{"n":"2004","v":"/year/2004"},{"n":"2003","v":"/year/2003"},{"n":"2002","v":"/year/2002"},{"n":"2001","v":"/year/2001"},{"n":"2000","v":"/year/2000"},{"n":"90年代","v":"/year/90年代"}]},{"key":"by","name":"排序","value":[{"n":"时间排序","v":"/by/time"},{"n":"人气排序","v":"/by/hits"},{"n":"豆瓣排序","v":"/by/score"}]}],
		"Series":[{"key":"class","name":"类型","value":[{"n":"全部","v":""},{"n":"古装","v":"/class/古装"},{"n":"剧情","v":"/class/剧情"},{"n":"喜剧","v":"/class/喜剧"},{"n":"惊悚","v":"/class/惊悚"},{"n":"动作","v":"/class/动作"},{"n":"爱情","v":"/class/爱情"},{"n":"犯罪","v":"/class/犯罪"},{"n":"恐怖","v":"/class/恐怖"},{"n":"冒险","v":"/class/冒险"},{"n":"悬疑","v":"/class/悬疑"},{"n":"科幻","v":"/class/科幻"},{"n":"家庭","v":"/class/家庭"},{"n":"奇幻","v":"/class/奇幻"},,{"n":"战争","v":"/class/战争"},{"n":"历史","v":"/class/历史"},{"n":"传记","v":"/class/传记"},{"n":"音乐","v":"/class/音乐"},{"n":"歌舞","v":"/class/歌舞"},{"n":"短片","v":"短片"},{"n":"西部","v":"西部"},{"n":"灾难","v":"/class/灾难"},{"n":"情色","v":"/class/情色"},{"n":"同性","v":"/class/同性"},{"n":"儿童","v":"/class/儿童"},{"n":"纪录片","v":"/class/纪录"}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""},{"n":"大陆","v":"/area/大陆"},{"n":"香港","v":"/area/香港"},{"n":"美国","v":"/area/美国"}]},{"key":"year","name":"年代","value":[{"n":"全部","v":""},{"n":"2024","v":"/year/2024"},{"n":"2023","v":"/year/2023"},{"n":"2022","v":"/year/2022"},{"n":"2021","v":"/year/2021"},{"n":"2020","v":"/year/2020"},{"n":"2019","v":"/year/2019"},{"n":"2018","v":"/year/2018"},{"n":"2017","v":"/year/2017"},{"n":"2016","v":"/year/2016"},{"n":"2015","v":"/year/2015"},{"n":"2014","v":"/year/2014"},{"n":"2013","v":"/year/2013"},{"n":"2012","v":"/year/2012"},{"n":"2011","v":"/year/2011"},{"n":"2010","v":"/year/2010"},{"n":"2009","v":"/year/2009"},{"n":"2008","v":"/year/2008"},{"n":"2007","v":"/year/2007"},{"n":"2006","v":"/year/2006"},{"n":"2005","v":"/year/2005"},{"n":"2004","v":"/year/2004"},{"n":"2003","v":"/year/2003"},{"n":"2002","v":"/year/2002"},{"n":"2001","v":"/year/2001"},{"n":"2000","v":"/year/2000"},{"n":"90年代","v":"/year/90年代"}]},{"key":"by","name":"排序","value":[{"n":"时间排序","v":"/by/time"},{"n":"人气排序","v":"/by/hits"},{"n":"豆瓣排序","v":"/by/score"}]}],
		"variety":[{"key":"class","name":"类型","value":[{"n":"全部","v":""},{"n":"古装","v":"/class/古装"},{"n":"剧情","v":"/class/剧情"},{"n":"喜剧","v":"/class/喜剧"},{"n":"惊悚","v":"/class/惊悚"},{"n":"动作","v":"/class/动作"},{"n":"爱情","v":"/class/爱情"},{"n":"犯罪","v":"/class/犯罪"},{"n":"恐怖","v":"/class/恐怖"},{"n":"冒险","v":"/class/冒险"},{"n":"悬疑","v":"/class/悬疑"},{"n":"科幻","v":"/class/科幻"},{"n":"家庭","v":"/class/家庭"},{"n":"奇幻","v":"/class/奇幻"},,{"n":"战争","v":"/class/战争"},{"n":"历史","v":"/class/历史"},{"n":"传记","v":"/class/传记"},{"n":"音乐","v":"/class/音乐"},{"n":"歌舞","v":"/class/歌舞"},{"n":"短片","v":"短片"},{"n":"西部","v":"西部"},{"n":"灾难","v":"/class/灾难"},{"n":"情色","v":"/class/情色"},{"n":"同性","v":"/class/同性"},{"n":"儿童","v":"/class/儿童"},{"n":"纪录片","v":"/class/纪录"}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""},{"n":"大陆","v":"/area/大陆"},{"n":"香港","v":"/area/香港"},{"n":"美国","v":"/area/美国"}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""},{"n":"2024","v":"/year/2024"},{"n":"2023","v":"/year/2023"},{"n":"2022","v":"/year/2022"},{"n":"2021","v":"/year/2021"},{"n":"2020","v":"/year/2020"},{"n":"2019","v":"/year/2019"},{"n":"2018","v":"/year/2018"},{"n":"2017","v":"/year/2017"},{"n":"2016","v":"/year/2016"},{"n":"2015","v":"/year/2015"},{"n":"2014","v":"/year/2014"},{"n":"2013","v":"/year/2013"},{"n":"2012","v":"/year/2012"},{"n":"2011","v":"/year/2011"},{"n":"2010","v":"/year/2010"},{"n":"2009","v":"/year/2009"},{"n":"2008","v":"/year/2008"},{"n":"2007","v":"/year/2007"},{"n":"2006","v":"/year/2006"},{"n":"2005","v":"/year/2005"},{"n":"2004","v":"/year/2004"},{"n":"2003","v":"/year/2003"},{"n":"2002","v":"/year/2002"},{"n":"2001","v":"/year/2001"},{"n":"2000","v":"/year/2000"},{"n":"90年代","v":"/year/90年代"}]},{"key":"by","name":"排序","value":[{"n":"时间排序","v":"/by/time"},{"n":"人气排序","v":"/by/hits"},{"n":"豆瓣排序","v":"/by/score"}]}],
		"cartoon":[{"key":"class","name":"类型","value":[{"n":"全部","v":""},{"n":"古装","v":"/class/古装"},{"n":"剧情","v":"/class/剧情"},{"n":"喜剧","v":"/class/喜剧"},{"n":"惊悚","v":"/class/惊悚"},{"n":"动作","v":"/class/动作"},{"n":"爱情","v":"/class/爱情"},{"n":"犯罪","v":"/class/犯罪"},{"n":"恐怖","v":"/class/恐怖"},{"n":"冒险","v":"/class/冒险"},{"n":"悬疑","v":"/class/悬疑"},{"n":"科幻","v":"/class/科幻"},{"n":"家庭","v":"/class/家庭"},{"n":"奇幻","v":"/class/奇幻"},,{"n":"战争","v":"/class/战争"},{"n":"历史","v":"/class/历史"},{"n":"传记","v":"/class/传记"},{"n":"音乐","v":"/class/音乐"},{"n":"歌舞","v":"/class/歌舞"},{"n":"短片","v":"短片"},{"n":"西部","v":"西部"},{"n":"灾难","v":"/class/灾难"},{"n":"情色","v":"/class/情色"},{"n":"同性","v":"/class/同性"},{"n":"儿童","v":"/class/儿童"},{"n":"纪录片","v":"/class/纪录"}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""},{"n":"大陆","v":"/area/大陆"},{"n":"香港","v":"/area/香港"},{"n":"美国","v":"/area/美国"}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""},{"n":"2024","v":"/year/2024"},{"n":"2023","v":"/year/2023"},{"n":"2022","v":"/year/2022"},{"n":"2021","v":"/year/2021"},{"n":"2020","v":"/year/2020"},{"n":"2019","v":"/year/2019"},{"n":"2018","v":"/year/2018"},{"n":"2017","v":"/year/2017"},{"n":"2016","v":"/year/2016"},{"n":"2015","v":"/year/2015"},{"n":"2014","v":"/year/2014"},{"n":"2013","v":"/year/2013"},{"n":"2012","v":"/year/2012"},{"n":"2011","v":"/year/2011"},{"n":"2010","v":"/year/2010"},{"n":"2009","v":"/year/2009"},{"n":"2008","v":"/year/2008"},{"n":"2007","v":"/year/2007"},{"n":"2006","v":"/year/2006"},{"n":"2005","v":"/year/2005"},{"n":"2004","v":"/year/2004"},{"n":"2003","v":"/year/2003"},{"n":"2002","v":"/year/2002"},{"n":"2001","v":"/year/2001"},{"n":"2000","v":"/year/2000"},{"n":"90年代","v":"/year/90年代"}]},{"key":"by","name":"排序","value":[{"n":"时间排序","v":"/by/time"},{"n":"人气排序","v":"/by/hits"},{"n":"豆瓣排序","v":"/by/score"}]}]
		
	},


	searchUrl: '/vod/search/page/fypage/wd/**.html',
	//vod/search/page/2/wd/狂飙.html
	searchable:2,
	quickSearch:0,
	filterable:1,
	headers:{
		'User-Agent': 'MOBILE_UA'
	},
	timeout:5000,
	class_parse:'.nav-menu-items&&li:gt(0);a&&Text;a&&href;.*/(.*?).html',
	cate_exclude:'明星||专题||求片||网址+',
	play_parse:true,
	limit:30,
	推荐: '*',
	一级: '.module-items&&.module-item;a&&title;img&&data-original;.module-item-text&&Text;a&&href',
	二级: {"title":"h1&&Text;.tag-link&&Text",
	        "img":".module-item-pic&&img&&data-src",
			"desc":".video-info-items:eq(-2)&&Text;.video-info-items:eq(-1)&&Text;.video-info-items:eq(-2)&&Text;.video-info-items:eq(1)&&.video-info-item&&Text;.video-info-items:eq(0)&&.video-info-item&&Text",
			"content":".vod_content&&Text",
			"tabs":".swiper-wrapper",
			"lists":".module-row-one:eq(#id)&&.module-row-shortcuts&&a"
			},
//"tabs":".module-tab-item","lists":".module-player-list:eq(#id)&&.scroll-content&&a"},
	搜索: '.module-items .module-search-item;a&&title;img&&data-src;.video-serial&&Text;a&&href'
}
